
-- ============================================================
-- MIGRATION: Sync production schema with development
-- ============================================================

-- ============================================================
-- 1. NEW COLUMNS on existing tables
-- ============================================================

-- empresas: fiscal fields
ALTER TABLE public.empresas
  ADD COLUMN IF NOT EXISTS razao_social TEXT,
  ADD COLUMN IF NOT EXISTS nome_fantasia TEXT,
  ADD COLUMN IF NOT EXISTS inscricao_estadual TEXT,
  ADD COLUMN IF NOT EXISTS telefone TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT;

-- filiais: structured address for fiscal docs
ALTER TABLE public.filiais
  ADD COLUMN IF NOT EXISTS logradouro TEXT,
  ADD COLUMN IF NOT EXISTS numero TEXT,
  ADD COLUMN IF NOT EXISTS complemento TEXT,
  ADD COLUMN IF NOT EXISTS bairro TEXT,
  ADD COLUMN IF NOT EXISTS codigo_municipio_ibge TEXT;

-- nfes: validation and XML content
ALTER TABLE public.nfes
  ADD COLUMN IF NOT EXISTS xml_content TEXT,
  ADD COLUMN IF NOT EXISTS status_validacao TEXT DEFAULT 'pendente',
  ADD COLUMN IF NOT EXISTS validado_em TIMESTAMPTZ;

-- cargas: IE fields for remetente/destinatario
ALTER TABLE public.cargas
  ADD COLUMN IF NOT EXISTS remetente_inscricao_estadual TEXT,
  ADD COLUMN IF NOT EXISTS destinatario_inscricao_estadual TEXT;

-- enderecos_carga: IBGE municipality code
ALTER TABLE public.enderecos_carga
  ADD COLUMN IF NOT EXISTS codigo_municipio_ibge TEXT;

-- ctes: Focus NFe integration fields
ALTER TABLE public.ctes
  ADD COLUMN IF NOT EXISTS focus_ref TEXT,
  ADD COLUMN IF NOT EXISTS focus_status TEXT;

-- entregas: CTE automation fields
ALTER TABLE public.entregas
  ADD COLUMN IF NOT EXISTS cte_gerado_automaticamente BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS cte_tentativas_geracao INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cte_ultimo_erro TEXT;

-- ============================================================
-- 2. NEW TABLE: config_fiscal
-- ============================================================

CREATE TABLE IF NOT EXISTS public.config_fiscal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  empresa_id BIGINT NOT NULL UNIQUE REFERENCES public.empresas(id) ON DELETE CASCADE,
  cfop_estadual TEXT NOT NULL DEFAULT '5353',
  cfop_interestadual TEXT NOT NULL DEFAULT '6353',
  natureza_operacao TEXT NOT NULL DEFAULT 'PRESTACAO DE SERVICO DE TRANSPORTE',
  serie_cte INTEGER NOT NULL DEFAULT 1,
  proximo_numero_cte INTEGER NOT NULL DEFAULT 1,
  icms_situacao_tributaria TEXT NOT NULL DEFAULT '00',
  icms_aliquota NUMERIC(5,2) NOT NULL DEFAULT 0.00,
  icms_base_calculo_percentual NUMERIC(5,2) NOT NULL DEFAULT 100.00,
  tomador_padrao TEXT NOT NULL DEFAULT '0',
  tipo_servico INTEGER NOT NULL DEFAULT 0,
  ambiente INTEGER NOT NULL DEFAULT 2,
  regime_tributario_emitente INTEGER NOT NULL DEFAULT 3,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN public.config_fiscal.regime_tributario_emitente
  IS '1 = Simples Nacional, 3 = Regime Normal';
COMMENT ON COLUMN public.config_fiscal.icms_base_calculo_percentual
  IS 'Percentual da base de calculo do ICMS (ex: 100.00 = base integral)';
COMMENT ON COLUMN public.config_fiscal.ambiente
  IS '1 = Producao, 2 = Homologacao';

ALTER TABLE public.config_fiscal ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view config for their empresa"
  ON public.config_fiscal FOR SELECT
  USING (user_belongs_to_empresa(auth.uid(), empresa_id));

CREATE POLICY "Users can insert config for their empresa"
  ON public.config_fiscal FOR INSERT
  WITH CHECK (user_belongs_to_empresa(auth.uid(), empresa_id));

CREATE POLICY "Users can update config for their empresa"
  ON public.config_fiscal FOR UPDATE
  USING (user_belongs_to_empresa(auth.uid(), empresa_id));

CREATE TRIGGER update_config_fiscal_updated_at
  BEFORE UPDATE ON public.config_fiscal
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- 3. NEW TABLE: mdfes
-- ============================================================

CREATE TABLE IF NOT EXISTS public.mdfes (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  viagem_id UUID NOT NULL REFERENCES public.viagens(id) ON DELETE CASCADE,
  empresa_id BIGINT REFERENCES public.empresas(id),
  numero TEXT,
  chave_acesso TEXT,
  focus_ref TEXT,
  status TEXT DEFAULT 'pendente',
  pdf_path TEXT,
  xml_path TEXT,
  erro TEXT,
  encerrado_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.mdfes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated"
  ON public.mdfes FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE INDEX idx_mdfes_viagem_id ON public.mdfes(viagem_id);
CREATE INDEX idx_mdfes_empresa_id ON public.mdfes(empresa_id);

CREATE TRIGGER update_mdfes_updated_at
  BEFORE UPDATE ON public.mdfes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================
-- 4. STORAGE: mdfes bucket
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('mdfes', 'mdfes', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Authenticated users can upload mdfes"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'mdfes' AND auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can read mdfes"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'mdfes' AND auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can update mdfes"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'mdfes' AND auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can delete mdfes"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'mdfes' AND auth.uid() IS NOT NULL);
